version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: prod
    container_name: backend
    networks:
      - backend
    ports:
      - 8000:8000
    command: >
      sh -c "sleep 20 && python /app/load_data.py && gunicorn -w 4 -b 0.0.0.0 books:create_app"
  
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  backend:
    name: backend_network
