"""data load

Revision ID: 5140b08306bb
Revises: 77ea9eee68b7
Create Date: 2023-08-28 01:16:01.976791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import csv


# revision identifiers, used by Alembic.
revision: str = '5140b08306bb'
down_revision: Union[str, None] = '77ea9eee68b7'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
     # Abre el archivo CSV y lee los datos
    with open('backend\books\database_files\authors.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        data_to_insert = [dict(row) for row in reader]

    # Inserta los datos en la tabla utilizando op.bulk_insert
    op.bulk_insert(
        'authors',  # Nombre de la tabla
        data_to_insert  # Lista de diccionarios con los datos
    )

    with open('backend\books\database_files\books.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        data_to_insert = [dict(row) for row in reader]

    # Inserta los datos en la tabla utilizando op.bulk_insert
    op.bulk_insert(
        'books',  # Nombre de la tabla
        data_to_insert  # Lista de diccionarios con los datos
    )

    with open('backend\books\database_files\ratings.csv', 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        data_to_insert = [dict(row) for row in reader]

    # Inserta los datos en la tabla utilizando op.bulk_insert
    op.bulk_insert(
        'ratings',  # Nombre de la tabla
        data_to_insert  # Lista de diccionarios con los datos
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
